@host = http://127.0.0.1:8080
@endpoint = tasks
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2VhNTEyYzZiODg2NjkyZGQ5YzIxZGIiLCJpYXQiOjE2NzYzMDA4NDAsImV4cCI6MTY3NjMwMTE0MH0.o2By2VPjoSWQM6OlCtpBN0M_0glNVrA79GNwCBBNsc4
@taskId = 63ea523c6b886692dd9c21de


### Get all tasks
GET {{host}}/{{endpoint}}?limit=5&offset=0
Content-Type: application/json
Authorization: bearer {{token}}

### Get task by id
GET {{host}}/{{endpoint}}/{{taskId}}
Content-Type: application/json
Authorization: bearer {{token}}

###Create Task
Post {{host}}/{{endpoint}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title" : "Tarea2",
    "description" : "Descripcion de la tarea2",
    "status" : false,
    "deadline" : "2023-03-22T03:00:00.000Z",
    "comments" : "Comentarios para la tarea 2",
    "tags" : ["work","tasks"]
}

###Update Task
PUT {{host}}/{{endpoint}}/{{taskId}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "comments" : "Tarea 2 update comentarios"
}

###Delete Task
DELETE  {{host}}/{{endpoint}}/{{taskId}}
Content-Type: application/json
Authorization: bearer {{token}}