@host = http://127.0.0.1:8080
@endpoint = tasks
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2U4NTMyNjkxMmM5MDU2OGU5NjkxYjAiLCJpYXQiOjE2NzYyNDA2MjgsImV4cCI6MTY3NjI0MjQyOH0.NvNfsbY1ynWTO6at6zDuUQBlTf3gC-9FYd99qoOLcEU
@taskId = 63e951eed7a7626d32741395


### Get all tasks
GET {{host}}/{{endpoint}}?limit=5&offset=0
Content-Type: application/json
Authorization: bearer {{token}}

### Get task by id
GET {{host}}/{{endpoint}}/{{taskId}}
Content-Type: application/json
Authorization: bearer {{token}}

###Create Task
Post {{host}}/{{endpoint}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title" : "Tarea2",
    "description" : "Descripcion de la tarea2",
    "status" : false,
    "deadline" : "2023-03-22T03:00:00.000Z",
    "comments" : "Comentarios para la tarea 1",
    "tags" : ["work","tasks"]
}