@host = http://127.0.0.1:8080
@endpoint = tasks
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2U4NTMyNjkxMmM5MDU2OGU5NjkxYjAiLCJpYXQiOjE2NzYyMjk2NzEsImV4cCI6MTY3NjIzMTQ3MX0.W7rGBmBPhEyC3DrzF7O5FqE_7SFohrNSHfZk4-n1m28


###Create Task
Post {{host}}/{{endpoint}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title" : "Tarea1",
    "description" : "Descripcion de la tarea1",
    "status" : false,
    "deadline" : "2023-03-22T03:00:00.000Z",
    "comments" : "Comentarios para la tarea 1",
    "tags" : ["work","tasks"]
}